### ISSUE TITLE
Initial load of a VST Plugin's Interface results in some momentary a/v stutter

### ISSUE THREAD

**Issue by iesv** [obsproject/obs-vst#103]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

https://obsproject.com/logs/Y73aCxbnghYkPW7w

### Expected Behavior

I hope it doesn't get lag. Just like OBS 27.1.3.

### Current Behavior

The vst plugin of OBS 27.2 appears stutters/lags when clicking the drop-down menu.

### Steps to Reproduce

1. open vst pluing filters of VLC
2. click the drop-down menu
3. select the nectar 3
4. open plug-in interface
5. it appears stutters/lags

### Anything else we should know?

Each time after clicking the drop-down menu, the screen or sound will appear to be delayed. But the OBS 27.1.3 doesn't.

**Comment by WizardCM** [comment]
Alright, I can confirm this with a few different plugins - initial load of a VST (opening its UI) can result in almost half a second of stutter. After that, there's an even smaller (near non-existent) stutter. I've moved this to the correct repository, and I'll do further testing later to see which commit introduced it. Thanks for confirming it occurs as early as Beta 1, that helps greatly.

**Comment by iesv** [comment]
My pleasure!

Matt Gajownik ***@***.***> 于2022年1月12日周三 10:31写道：

**Comment by iesvme** [comment]
My pleasure!

**Comment by walker-WSH** [comment]
I also meet this block while loading many VST plugins.

I debugged it and find sometimes VSTPluginMain() takes 100~300ms which causes UI thread block.
Typically，about 4s will be taken on VSTPluginMain() of  **“FL Studio VSTi (Multi).dll”**

How about moving loading VST into worker thread ?

[FL Studio VSTi (Multi).zip](https://github.com/obsproject/obs-vst/files/7851368/FL.Studio.VSTi.Multi.zip)

**Comment by WizardCM** [comment]
After some bisecting and a lot of testing, this issue was introduced in 1dde4c37a5d. My guess is that the mutex is causing issues.

**Comment by walker-WSH** [comment]
> After some bisecting and a lot of testing, this issue was introduced in [1dde4c3](https://github.com/obsproject/obs-vst/commit/1dde4c37a5d40dc1486c84ee544531cf807ca35d). My guess is that the mutex is causing issues.



Improvement tips:
1. since delete effect and openEditor() are both called from UI thread, so the lock in openEditor() can be removed;
2. in loadEffectFromPath, since loading VST can't be finished soon, so lock region could be reduced. That is to say, loadEffect() should be called outside of lock.

**Comment by WizardCM** [comment]
@walker-WSH Would you be willing to experiment and PR a fix? Unfortunately I don't know the VST code that well.

**Comment by walker-WSH** [comment]
> @walker-WSH Would you be willing to experiment and PR a fix? Unfortunately I don't know the VST code that well.




I will arrange the lock tomorrow.

In fact，effect is always changed in UI thread，so lock should only be added for these funcs:
1. access effect outside of UI thread
2. modify effect
