### ISSUE TITLE
Trouble loading SPL De-Verb on OSX

### ISSUE THREAD

**Issue by DDRBoxman** [obsproject/obs-vst#29]
"malformed mach-o image: __TEXT segment maps start of file but is writable"

https://www.plugin-alliance.com/en/products/spl_de-verb.html

**Comment by DDRBoxman** [comment]
Loads fine in Adobe Audition

**Comment by DDRBoxman** [comment]
Works in giada too

**Comment by c3r1c3** [comment]
Does it work on Windows (OBS or another host)?

**Comment by DDRBoxman** [comment]
I re-installed it through the plugin alliance installation manager instead of downloading the demo directly and it loads up fine now.
