### ISSUE TITLE
Plugin uses fixed VST paths (Windows)

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-vst#36]
Currently it is not possible to use plugins outside of the C:\ drive without requiring either a symlink or installing them to the C:\ drive. Ideally the user should be able to configure where these are loaded from (via a frontend tools option or similar).

Alternatively, you can try reading registry keys on Windows, FL Studio for example sets the following:

- HKCU/Software/Image-Line/Shared/Plugins/FL Studio/VstDir (32-bit)
- HKCU/Software/Image-Line/Shared/Plugins/FL Studio/VstDir64 (64-bit)

See: https://github.com/DDRBoxman/obs-vst/blob/62bf634c1ff2ff47280207bd4af253b2142af427/obs-vst.cpp#L134

**Comment by DDRBoxman** [comment]
duplicate #16
