### ISSUE TITLE
Plugin settings dont load on boot, always reverts to init patch.

### ISSUE THREAD

**Issue by ProtostarMusic** [obsproject/obs-vst#37]
Been using some scenes with reverb + delay on my voice (kilohearts rvb and delay) but whenever rebooting OBS the VSTs always revert to init patch, would be a good feature to be able to remember what patch was last used.
![2017-02-28_17-15-07](https://cloud.githubusercontent.com/assets/19961432/23438701/f5c6a9bc-fe0a-11e6-8498-c4f90906534f.gif)

**Comment by DDRBoxman** [comment]
https://obsproject.com/forum/threads/vst-plug-in-settings-not-saving.64282/

**Comment by DDRBoxman** [comment]
#35

**Comment by DDRBoxman** [comment]
https://github.com/DDRBoxman/obs-vst/commit/9f53ce89916dad523c730594626f14ba856d540f
