### ISSUE TITLE
Plugins in ~/.vst not autodetected

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-vst#64]
Reading from the source code, I assumed that obs-vst would detect a plugin in ``~/.vst/``. I think that ``~`` is not expanded in https://github.com/obsproject/obs-vst/blob/83e1bf241007480a796c0c3f65018d1f0e482447/obs-vst.cpp#L178.

Indeed, if I manually set ``VST_PATH`` to the expansion on ``~/.vst/``, detection works, but if I set it to literally that string, it does not.

**Comment by tytan652** [comment]
I think you maybe had multiple paths in VST_PATH and obs-vst don't manage right now multiple path in this env var.
