### ISSUE TITLE
Support more VST folders

### ISSUE THREAD

**Issue by DDRBoxman** [obsproject/obs-vst#7]
C:\Program Files\Common Files\Steinberg\Shared Components
C:\Program Files\Common Files\VST2
C:\Program Files\Common Files\VSTPlugins

~/Library/Audio/Plugins/VST

**Comment by DDRBoxman** [comment]
C:\Program Files\VSTPlugins
C:\Program Files\Steinberg\VSTPlugins

**Comment by c3r1c3** [comment]
You should be able to close... most of this one?
