### ISSUE TITLE
obs crashes when add some vst plugins

### ISSUE THREAD

**Issue by Usunshine** [obsproject/obs-vst#74]
**Platform**
Operating system and version: Windows 10 x64 
OBS Studio version: Obs 26.1.1 64-bit (Also occur on older version).

**Expected Behavior**
plugin work fine

**Current Behavior**
obs crashes

**Steps to Reproduce**

1. install vst plugin "WaveShell3-VST 11.0_x64.dll" to the computer.
2. add VST2.x plugin filter to any sound source and choose "WaveShell3-VST 11.0_x64.dll" or "pitchproof-x64.dll"
3. obs crashes.

**Log:** 
[Crash 2021-02-02 13-55-56.txt](https://github.com/obsproject/obs-vst/files/5909020/Crash.2021-02-02.13-55-56.txt)

**Comment by walker-WSH** [comment]
This issue is not closed automatically even the related pr has been merged.
@jp9000
