### ISSUE TITLE
VST2 non-FX/synthesizer plugins crash when added as a filter in audio sources

### ISSUE THREAD

**Issue by 1011025m** [obsproject/obs-vst#84]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/Zqcy6VZS9zjPkaF7

### Expected Behavior

Giving out an prompt, saying that the added plugin is not an FX plugin and should not be added as a filter on audio sources.

### Current Behavior

OBS Studio crashed, in some cases, immediately closes itself (so that I cannot click on the error log prompt)

### Steps to Reproduce

1. Add an audio source
2. Open filters, add VST 2.x plugin filter
3. Pick a non-FX VST plugin

### Anything else we should know?

I tested it with multiple synthesizers. Here's a few that crashed:

- Synapse Audio DUNE 3
- Reveal Sound Spire
- XFer Records SerumFX (Serum didn't crash but didn't work either)
- U-he Zebra2

Surprisingly, Sylenth1 didn't crash at all and actually works without problems...

DAWs like FL Studio have prompts if you insert non-FX plugins into the mixer, I hope this can be added to OBS as well.

**Comment by walker-WSH** [comment]
> Can confirm similar behavior in 26.1.2 running on macOS Catalina 10.15.6 - Crashed when trying to load Native Instrument's Kontakt. HOWEVER, it did not crash when loading Arturia's B-3 V.
> 
> Link to crash log: https://docs.google.com/document/d/1P0-WeJW0cn68eHZ1Wmv8eR7YRor2clbtdgPHTe_eO-I/edit?usp=sharing

 Can you send me the non-FX dll ?  I can't find out it.
Or you can have a try with latest obs-vst as I have fixed several crashes.

**Comment by walker-WSH** [comment]
About "U-he Zebra2", after installing it, there are 4 dlls:
![1637892181](https://user-images.githubusercontent.com/18413354/143515883-65de65bf-1f31-40c7-9356-e1eaf47aaeab.png)

The crash caused by the front two dlls has been fixed in https://github.com/obsproject/obs-vst/pull/90.
The left two dlls will also cause OBS crash while calling effect->processReplacing

**Comment by walker-WSH** [comment]
PR is created for this crash. https://github.com/obsproject/obs-vst/pull/95

I can just download "U-he Zebra2" and "Reveal Sound Spire".
Will any one help test “Reveal Sound Spire” ?

**Comment by 1011025m** [comment]
> I can just download "U-he Zebra2" and "Reveal Sound Spire". Will any one help test “Reveal Sound Spire” ?

I can test if you can provide a compiled binary file

**Comment by walker-WSH** [comment]
> > I can just download "U-he Zebra2" and "Reveal Sound Spire". Will any one help test “Reveal Sound Spire” ?
> 
> I can test if you can provide a compiled binary file

Here is the compiled file. It is available with OBS-27.1.3
[obs-vst.zip](https://github.com/obsproject/obs-vst/files/7623599/obs-vst.zip)

Please replace the file with it :
D:\Program Files\obs-studio\obs-plugins\64bit\obs-vst.dll

If OBS still crash, please upload the dll of “Reveal Sound Spire” for debug. 
Thanks

**Comment by 1011025m** [comment]
> If OBS still crash, please upload the dll of “Reveal Sound Spire” for debug.

I can't upload it because it is proprietary software, though I can provide you with a log file.

**Comment by 1011025m** [comment]
Reporting back with the results.
Almost all plugins survived the test, which is great!
All mainstream plugins that I have did not crash either.
I didn't test the plugins outputted the sound properly, will do some tests later.

Synthesizers are not supposed to be used as an effect though. If it's possible, make a pop-up window for a warning.

Much thanks
Attached log files for your reference
[2021-11-30 15-45-33.txt](https://github.com/obsproject/obs-vst/files/7623944/2021-11-30.15-45-33.txt)
[2021-11-30 15-52-37.txt](https://github.com/obsproject/obs-vst/files/7623945/2021-11-30.15-52-37.txt)

**Comment by walker-WSH** [comment]
> Reporting back with the results. Almost all plugins survived the test, which is great! All mainstream plugins that I have did not crash either. I didn't test the plugins outputted the sound properly, will do some tests later.
> 
> Synthesizers are not supposed to be used as an effect though. If it's possible, make a pop-up window for a warning.
> 
> Much thanks Attached log files for your reference [2021-11-30 15-45-33.txt](https://github.com/obsproject/obs-vst/files/7623944/2021-11-30.15-45-33.txt) [2021-11-30 15-52-37.txt](https://github.com/obsproject/obs-vst/files/7623945/2021-11-30.15-52-37.txt)

Thanks for your help.

In fact, not all vst plugins displayed in OBS are available.
If fail to initialize VST effect, logic will break to avoid OBS's crash. 

For this kind of vst plugin, **Audacity** generally remove it from VST list after scanning by child process.
I think this is a good feature.
