### ISSUE TITLE
There is a vst2 problem. vst3 is not working. it always crashes.

### ISSUE THREAD

**Issue by IBRAHIMASKAN** [obsproject/obs-vst#87]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc6

### OBS Studio Version (Other)

26

### OBS Studio Log URL

----------------------------------------------------

### OBS Studio Crash Log URL

-----------------------------------------------------------

### Expected Behavior

Hello good day. I think the biggest problem, obs beautiful is missing (vst3) is not possible to use. vst2 crashes with some processes. I think it better be given priority to the vst 3 business. User base is formed for the future of obs. many software do not have this vst. When will the vst3 insert be added? what is the future plan? thanks everyone.

### Current Behavior

There is a vst2 problem. vst3 is not working. it always crashes.

### Steps to Reproduce

1.
2.
3.
...
Hello good day. I think the biggest problem, obs beautiful is missing (vst3) is not possible to use. vst2 crashes with some processes. I think it better be given priority to the vst 3 business. User base is formed for the future of obs. many software do not have this vst. When will the vst3 insert be added? what is the future plan? thanks everyone.

### Anything else we should know?

Hello good day. I think the biggest problem, obs beautiful is missing (vst3) is not possible to use. vst2 crashes with some processes. I think it better be given priority to the vst 3 business. User base is formed for the future of obs. many software do not have this vst. When will the vst3 insert be added? what is the future plan? thanks everyone.

**Comment by WizardCM** [comment]
This is not a valid bug report. Go [here](https://ideas.obsproject.com/) for feature requests.
